### ISSUE TITLE
et_reference only can't be exported

### ISSUE THREAD

**Issue by gabe-parrish** [Open-ET/openet-ssebop-beta#37]
image.interpolate can't handle an export call with only et_reference.

You have to ask for both et_reference and etf or something... The documentation suggests that you could ask for just et_reference, which is weird, but if you do you get a bug, so I'm making this issue.

**Comment by cgmorton** [comment]
@gabe-parrish Is this still an issue with the latest version of the code?

**Comment by macfriedrichs** [comment]
This is working now as of version 0.1.5. Tested.
