### ISSUE TITLE
Add scale factor defaults for user-input dT collections

### ISSUE THREAD

**Issue by macfriedrichs** [Open-ET/openet-ssebop-beta#41]
Need to determine most appropriate method to specify or pass through a scale factor in image class or at method function for string ID-based dT collections such as dTv6: ("projects/usgs-ssebop/dt/daymet_median_v6"), currently hardcoded.  This is related to model updates for v0.2.3 and beyond.

**Comment by cgmorton** [comment]
I added support for this to the image class but I'm not sure if it is needed in collection also.  Right now, if the scale factor is None or not set, it will default to 0.01 for the v6 dt asset and to 1.0 for all other assets.

**Comment by cgmorton** [comment]
I think this is closed now.  I'm reading the scale_factor property from the dt image collection if it exists, otherwise it is using a value of 1 for all dt sources that are set as image collection IDs starting with users or projects.
