### ISSUE TITLE
topwx_median_v0_default not found

### ISSUE THREAD

**Issue by spizwhiz** [Open-ET/openet-ssebop-beta#7]
When  trying to run the examples, the following error message is displayed when trying to display a thumbnail for ssebop_obj.etx  (ssebop.obj.ndvi works fine)

EEException                               Traceback (most recent call last)
<ipython-input-29-34450a3457f8> in <module>
      1 Image(url=ssebop_obj.etf \
----> 2           .getThumbURL({'min': 0.0, 'max': 1.2, 'palette': ','.join(et_palette)}),
      3       embed=True, format='png')

~\Anaconda2\envs\Py3.7\lib\site-packages\ee\image.py in getThumbURL(self, params)
    246         raise ee_exception.EEException(
    247             'The region parameter must be an array or a GeoJSON object.')
--> 248     return data.makeThumbUrl(data.getThumbId(params))
    249 
    250   # Deprecated spellings to match the JS library.

~\Anaconda2\envs\Py3.7\lib\site-packages\ee\data.py in getThumbId(params)
    534   if 'size' in request and isinstance(request['size'], (list, tuple)):
    535     request['size'] = 'x'.join(map(str, request['size']))
--> 536   return send_('/thumb', request)
    537 
    538 

~\Anaconda2\envs\Py3.7\lib\site-packages\ee\data.py in send_(path, params, opt_method, opt_raw)
   1184       raise ee_exception.EEException('Invalid JSON: %s' % content)
   1185     if 'error' in json_content:
-> 1186       raise ee_exception.EEException(json_content['error']['message'])
   1187     if 'data' not in content:
   1188       raise ee_exception.EEException('Malformed response: ' + str(content))

EEException: Image.load: Image asset 'projects/usgs-ssebop/tcorr_image/topowx_median_v0_default' not found.

**Comment by macfriedrichs** [comment]
Resolved. Added access permissions to default image asset. Subject to change.
